version: '2.3'

volumes:
  workspace:

networks:
  default:
    external:
      name: robot-ops_default

services:

  odas:
    build: ./odas
    image: wn1980/odas-ros${TAG}
    container_name: ros_odas_server
    init: true
    restart: unless-stopped
    privileged: true
    #depends_on: 
    #  - master
    #command: tail -f /dev/null
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://master:11311
      #- QT_X11_NO_MITSHM=1
      #- TURTLEBOT_3D_SENSOR=asus_xtion_pro
    devices:
      - "/dev:/dev"
      - "/dev/snd:/dev/snd"
    volumes:
      - "/dev:/dev"
      - "/dev/snd:/dev/snd"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
      - "./asoundrc.txt:/root/.asoundrc:rw"
      - "~/.gitconfig:/root/.gitconfig"
